# === Delivery Schedule ===
DELIVERY_DAY = "Tuesday"
DELIVERY_HOUR = 10
HOLIDAY = False

# === Delivery Constraints ===
MAX_ROUTE_DISTANCE_KM = 1000
MAX_ROUTE_DURATION_HOURS = 5
MAX_STOPS_PER_ROUTE = 25
MAX_DISTANCE_TO_ROAD_METERS = 1000

# === Routing Behavior ===
ASSUME_SPEED_KMPH = 30
